/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountingPeriods {
  company_id: string;
  end_date: string;
  fiscal_year_id: string;
  id: Generated<string>;
  is_adjustment: Generated<boolean>;
  is_locked: Generated<boolean>;
  locked_at: Timestamp | null;
  locked_by: string | null;
  name: string;
  period_no: number;
  start_date: string;
}

export interface AccountPeriodBalances {
  account_id: string;
  branch_id: Generated<string>;
  company_id: string;
  credit_total: Generated<Numeric>;
  debit_total: Generated<Numeric>;
  period_id: string;
}

export interface Accounts {
  cash_flow_category: string | null;
  class: string;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency_code: string | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_control: Generated<boolean>;
  is_postable: Generated<boolean>;
  is_system: Generated<boolean>;
  name: string;
  parent_id: string | null;
  requires_contact: Generated<boolean>;
  subtype: string | null;
  system_key: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface AdvanceAdjustments {
  adjustment_date: string;
  advance_id: string;
  amount: Numeric;
  approved_at: Timestamp | null;
  approved_by: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_no: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  narration: string | null;
  posted_at: Timestamp | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  side: string;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  target_id: string;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface Allocations {
  allocated_on: string;
  amount: Numeric;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  reversed_at: Timestamp | null;
  reversed_by: string | null;
  source_id: string;
  source_type: string;
  target_id: string;
  target_type: string;
}

export interface ApprovalActions {
  acted_at: Generated<Timestamp>;
  acted_by: string;
  action: string;
  comment: string | null;
  company_id: string;
  id: Generated<string>;
  request_id: string;
  step_no: number;
}

export interface ApprovalRequests {
  amount: Generated<Numeric>;
  company_id: string;
  completed_at: Timestamp | null;
  current_step: Generated<number>;
  doc_id: string;
  doc_ref: string | null;
  doc_type: string;
  id: Generated<string>;
  status: string;
  steps: Generated<Json>;
  submitted_at: Generated<Timestamp>;
  submitted_by: string;
  total_steps: Generated<number>;
  workflow_id: string | null;
}

export interface ApprovalSteps {
  company_id: string;
  id: Generated<string>;
  min_amount: Generated<Numeric>;
  name: string;
  role_id: string | null;
  step_no: number;
  workflow_id: string;
}

export interface ApprovalWorkflows {
  auto_approve: Generated<boolean>;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  doc_type: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface AuditLogs {
  action: string;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  company_id: string | null;
  entity: string;
  entity_id: string | null;
  hash: string;
  id: Generated<Int8>;
  ip: string | null;
  prev_hash: string | null;
  request_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthEvents {
  at: Generated<Timestamp>;
  detail: Json | null;
  email: string | null;
  event: string;
  id: Generated<Int8>;
  ip: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface Branches {
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_head_office: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface BsCalendar {
  ad_start: string;
  bs_month: number;
  bs_year: number;
  days: number;
  is_provisional: Generated<boolean>;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface Companies {
  abn: string | null;
  address: string | null;
  base_currency: string;
  business_type: string;
  calendar_mode: string;
  coa_template: Generated<string>;
  country: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  email: string | null;
  enforce_2fa_all: Generated<boolean>;
  fy_start_month: number;
  go_live_date: string | null;
  go_live_status: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  legal_name: string | null;
  name: string;
  pan: string | null;
  phone: string | null;
  self_approval_allowed: Generated<boolean>;
  tax_rounding: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  vat_no: string | null;
  version: Generated<number>;
}

export interface Contacts {
  abn: string | null;
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credit_limit: Numeric | null;
  currency_code: string | null;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  notes: string | null;
  pan: string | null;
  payment_terms_days: Generated<number>;
  phone: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  vat_no: string | null;
  version: Generated<number>;
}

export interface CorrectionRequests {
  approved_at: Timestamp | null;
  approved_by: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  correction_date: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_no: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  kind: string;
  posted_at: Timestamp | null;
  reason: string;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  target_id: string;
  target_ref: string | null;
  target_type: string;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface CostCentres {
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface CreditNoteLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  note_id: string;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface CreditNotes {
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  discount_total: Generated<Numeric>;
  doc_no: string | null;
  exempt_total: Generated<Numeric>;
  fx_rate: Generated<Numeric>;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  journal_entry_id: string | null;
  last_printed_at: Timestamp | null;
  note_date: string;
  notes: string | null;
  original_invoice_id: string | null;
  posted_at: Timestamp | null;
  price_includes_tax: Generated<boolean>;
  print_count: Generated<number>;
  reason: string | null;
  refund_account_id: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  rounding_adjustment: Generated<Numeric>;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  unallocated_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  zero_rated_total: Generated<Numeric>;
}

export interface Currencies {
  code: string;
  decimals: Generated<number>;
  name: string;
  symbol: string | null;
}

export interface DebitNoteLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  note_id: string;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface DebitNotes {
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  discount_total: Generated<Numeric>;
  doc_no: string | null;
  exempt_total: Generated<Numeric>;
  fx_rate: Generated<Numeric>;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  journal_entry_id: string | null;
  last_printed_at: Timestamp | null;
  non_claimable_tax: Generated<Numeric>;
  note_date: string;
  notes: string | null;
  original_bill_id: string | null;
  posted_at: Timestamp | null;
  price_includes_tax: Generated<boolean>;
  print_count: Generated<number>;
  reason: string | null;
  refund_account_id: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  rounding_adjustment: Generated<Numeric>;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  subtotal: Generated<Numeric>;
  supplier_ref: string | null;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  unallocated_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  zero_rated_total: Generated<Numeric>;
}

export interface ExpenseLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  expense_id: string;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface Expenses {
  amount_due: Generated<Numeric>;
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  discount_total: Generated<Numeric>;
  doc_no: string | null;
  exempt_total: Generated<Numeric>;
  expense_date: string;
  fx_rate: Generated<Numeric>;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  journal_entry_id: string | null;
  kind: string;
  last_printed_at: Timestamp | null;
  narration: string | null;
  non_claimable_tax: Generated<Numeric>;
  paid_from_account_id: string | null;
  posted_at: Timestamp | null;
  price_includes_tax: Generated<boolean>;
  print_count: Generated<number>;
  project_id: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  rounding_adjustment: Generated<Numeric>;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  subtotal: Generated<Numeric>;
  supplier_invoice_no: string | null;
  supplier_pan: string | null;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  zero_rated_total: Generated<Numeric>;
}

export interface FiscalYears {
  closed_at: Timestamp | null;
  closed_by: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_date: string;
  id: Generated<string>;
  label: string;
  start_date: string;
  status: Generated<string>;
}

export interface GoodsReceiptLines {
  company_id: string;
  description: string | null;
  id: Generated<string>;
  item_id: string;
  line_no: number;
  po_line_id: string | null;
  quantity: Numeric;
  receipt_id: string;
}

export interface GoodsReceipts {
  branch_id: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_no: string;
  id: Generated<string>;
  notes: string | null;
  purchase_order_id: string | null;
  receipt_date: string;
  status: Generated<string>;
  supplier_ref: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface IdempotencyKeys {
  company_id: string;
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response: Json | null;
  status_code: number | null;
  user_id: string;
}

export interface IntegrationOutbox {
  attempts: Generated<number>;
  company_id: string | null;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Json;
  status: Generated<string>;
  target: string;
}

export interface Items {
  barcode: string | null;
  cogs_account_id: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  default_tax_code_id: string | null;
  description: string | null;
  hs_code: string | null;
  id: Generated<string>;
  inventory_account_id: string | null;
  is_active: Generated<boolean>;
  is_stock_tracked: Generated<boolean>;
  name: string;
  purchase_account_id: string | null;
  purchase_price: Generated<Numeric>;
  reorder_level: Numeric | null;
  sales_account_id: string | null;
  sales_price: Generated<Numeric>;
  sku: string;
  tax_applicability: string;
  type: string;
  uom_code: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface JournalEntries {
  approved_by: string | null;
  branch_id: string | null;
  company_id: string;
  created_txid: Generated<Int8>;
  entry_date: string;
  entry_no: string;
  id: Generated<string>;
  is_opening: Generated<boolean>;
  narration: string | null;
  period_id: string;
  posted_at: Generated<Timestamp>;
  posted_by: string;
  reversal_of: string | null;
  reversed_by_entry_id: string | null;
  source_id: string | null;
  source_no: string | null;
  source_type: string;
  status: Generated<string>;
  total: Numeric;
}

export interface JournalLines {
  account_id: string;
  amount_fc: Numeric | null;
  company_id: string;
  contact_id: string | null;
  cost_centre_id: string | null;
  credit: Generated<Numeric>;
  currency_code: string;
  debit: Generated<Numeric>;
  description: string | null;
  entry_date: string;
  entry_id: string;
  fx_rate: Generated<Numeric>;
  id: Generated<string>;
  item_id: string | null;
  line_no: number;
  project_id: string | null;
  tax_code_id: string | null;
}

export interface ManualJournalLines {
  account_id: string;
  company_id: string;
  contact_id: string | null;
  cost_centre_id: string | null;
  credit: Generated<Numeric>;
  debit: Generated<Numeric>;
  description: string | null;
  id: Generated<string>;
  journal_id: string;
  line_no: number;
}

export interface ManualJournals {
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_no: string | null;
  id: Generated<string>;
  journal_date: string;
  journal_entry_id: string | null;
  narration: string;
  posted_at: Timestamp | null;
  reference: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface NumberSeries {
  company_id: string;
  doc_type: string;
  fiscal_year_id: string;
  id: Generated<string>;
  next_no: Generated<number>;
  padding: Generated<number>;
  prefix: string;
}

export interface OpeningBalanceLines {
  account_id: string | null;
  company_id: string;
  contact_id: string | null;
  credit: Generated<Numeric>;
  debit: Generated<Numeric>;
  description: string | null;
  doc_date: string | null;
  due_date: string | null;
  id: Generated<string>;
  kind: string;
  line_no: number;
  opening_id: string;
  reference: string | null;
}

export interface OpeningBalances {
  approved_at: Timestamp | null;
  approved_by: string | null;
  as_of_date: string;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_no: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  narration: string | null;
  obe_difference: Generated<Numeric>;
  posted_at: Timestamp | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface PasswordResets {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Payments {
  amount: Numeric;
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  cheque_no: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  discount_amount: Generated<Numeric>;
  doc_no: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  kind: Generated<string>;
  last_printed_at: Timestamp | null;
  narration: string | null;
  paid_from_account_id: string;
  payment_date: string;
  planned_allocations: Generated<Json>;
  posted_at: Timestamp | null;
  print_count: Generated<number>;
  reference: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  tds_amount: Generated<Numeric>;
  tds_code_id: string | null;
  total: Generated<Numeric>;
  unallocated_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface Permissions {
  code: string;
  description: string;
}

export interface PostingRules {
  account_ref: string;
  company_id: string | null;
  description: string | null;
  id: Generated<string>;
  role: string;
  side: string;
  source_type: string;
}

export interface PurchaseBillLines {
  account_id: string | null;
  bill_id: string;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface PurchaseBills {
  amount_due: Generated<Numeric>;
  approved_at: Timestamp | null;
  approved_by: string | null;
  bill_date: string;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  discount_total: Generated<Numeric>;
  doc_no: string | null;
  due_date: string | null;
  exempt_total: Generated<Numeric>;
  fx_rate: Generated<Numeric>;
  goods_receipt_id: string | null;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  is_opening: Generated<boolean>;
  journal_entry_id: string | null;
  last_printed_at: Timestamp | null;
  non_claimable_tax: Generated<Numeric>;
  notes: string | null;
  ocr_job_id: string | null;
  posted_at: Timestamp | null;
  price_includes_tax: Generated<boolean>;
  print_count: Generated<number>;
  project_id: string | null;
  purchase_order_id: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  rounding_adjustment: Generated<Numeric>;
  source_document_id: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  subtotal: Generated<Numeric>;
  supplier_invoice_date: string | null;
  supplier_invoice_no: string;
  supplier_pan: string | null;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  zero_rated_total: Generated<Numeric>;
}

export interface PurchaseOrderLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  order_id: string;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface PurchaseOrders {
  branch_id: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  doc_no: string;
  expected_date: string | null;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  notes: string | null;
  order_date: string;
  price_includes_tax: Generated<boolean>;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface Receipts {
  amount: Numeric;
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  cheque_no: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  deposit_account_id: string;
  discount_amount: Generated<Numeric>;
  doc_no: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  kind: Generated<string>;
  last_printed_at: Timestamp | null;
  narration: string | null;
  planned_allocations: Generated<Json>;
  posted_at: Timestamp | null;
  print_count: Generated<number>;
  receipt_date: string;
  reference: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  tds_amount: Generated<Numeric>;
  tds_code_id: string | null;
  total: Generated<Numeric>;
  unallocated_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface RolePermissions {
  company_id: string;
  permission_code: string;
  role_id: string;
}

export interface Roles {
  approval_limit: Numeric | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  key: string | null;
  name: string;
  requires_2fa: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface SalesInvoiceLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  invoice_id: string;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface SalesInvoices {
  amount_due: Generated<Numeric>;
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string | null;
  buyer_address: string | null;
  buyer_name: string | null;
  buyer_pan: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  cash_account_id: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  customer_ref: string | null;
  discount_total: Generated<Numeric>;
  doc_no: string | null;
  due_date: string | null;
  exempt_total: Generated<Numeric>;
  fx_rate: Generated<Numeric>;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  invoice_date: string;
  is_opening: Generated<boolean>;
  journal_entry_id: string | null;
  last_printed_at: Timestamp | null;
  notes: string | null;
  posted_at: Timestamp | null;
  price_includes_tax: Generated<boolean>;
  print_count: Generated<number>;
  project_id: string | null;
  reversal_entry_id: string | null;
  reversed_at: Timestamp | null;
  rounding_adjustment: Generated<Numeric>;
  sales_order_id: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  zero_rated_total: Generated<Numeric>;
}

export interface SalesOrderLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  order_id: string;
  project_id: string | null;
  quantity: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface SalesOrders {
  branch_id: string | null;
  company_id: string;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  customer_ref: string | null;
  doc_no: string;
  expected_date: string | null;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  notes: string | null;
  order_date: string;
  price_includes_tax: Generated<boolean>;
  quote_id: string | null;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface SalesQuoteLines {
  account_id: string | null;
  company_id: string;
  cost_centre_id: string | null;
  description: string | null;
  discount_amount: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  id: Generated<string>;
  is_claimable: Generated<boolean>;
  item_id: string | null;
  line_no: number;
  net_amount: Generated<Numeric>;
  project_id: string | null;
  quantity: Generated<Numeric>;
  quote_id: string;
  tax_amount: Generated<Numeric>;
  tax_code_id: string | null;
  tax_rate: Generated<Numeric>;
  tax_type: Generated<string>;
  total_amount: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface SalesQuotes {
  branch_id: string | null;
  company_id: string;
  contact_id: string;
  converted_to_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency_code: string;
  doc_no: string;
  grand_total: Generated<Numeric>;
  id: Generated<string>;
  notes: string | null;
  price_includes_tax: Generated<boolean>;
  quote_date: string;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  valid_until: string | null;
  version: Generated<number>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip: string | null;
  last_used_at: Generated<Timestamp>;
  mfa_verified: Generated<boolean>;
  refresh_hash: string;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  step_up_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface TaxCodes {
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  input_account_id: string | null;
  is_active: Generated<boolean>;
  is_claimable: Generated<boolean>;
  name: string;
  output_account_id: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface TaxRates {
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  effective_from: string;
  effective_to: string | null;
  id: Generated<string>;
  rate: Numeric;
  tax_code_id: string;
}

export interface TdsCodes {
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  payable_account_id: string;
  rate: Numeric;
  receivable_account_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface Uoms {
  code: string;
  name: string;
}

export interface UserCompanies {
  company_id: string;
  default_branch_id: string | null;
  is_active: Generated<boolean>;
  joined_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserRoles {
  company_id: string;
  role_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  failed_attempts: Generated<number>;
  full_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_super_admin: Generated<boolean>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  mfa_pending_secret_enc: string | null;
  mfa_recovery_hashes: Generated<Json>;
  mfa_secret_enc: string | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DB {
  account_period_balances: AccountPeriodBalances;
  accounting_periods: AccountingPeriods;
  accounts: Accounts;
  advance_adjustments: AdvanceAdjustments;
  allocations: Allocations;
  approval_actions: ApprovalActions;
  approval_requests: ApprovalRequests;
  approval_steps: ApprovalSteps;
  approval_workflows: ApprovalWorkflows;
  audit_logs: AuditLogs;
  auth_events: AuthEvents;
  branches: Branches;
  bs_calendar: BsCalendar;
  companies: Companies;
  contacts: Contacts;
  correction_requests: CorrectionRequests;
  cost_centres: CostCentres;
  credit_note_lines: CreditNoteLines;
  credit_notes: CreditNotes;
  currencies: Currencies;
  debit_note_lines: DebitNoteLines;
  debit_notes: DebitNotes;
  expense_lines: ExpenseLines;
  expenses: Expenses;
  fiscal_years: FiscalYears;
  goods_receipt_lines: GoodsReceiptLines;
  goods_receipts: GoodsReceipts;
  idempotency_keys: IdempotencyKeys;
  integration_outbox: IntegrationOutbox;
  items: Items;
  journal_entries: JournalEntries;
  journal_lines: JournalLines;
  manual_journal_lines: ManualJournalLines;
  manual_journals: ManualJournals;
  number_series: NumberSeries;
  opening_balance_lines: OpeningBalanceLines;
  opening_balances: OpeningBalances;
  password_resets: PasswordResets;
  payments: Payments;
  permissions: Permissions;
  posting_rules: PostingRules;
  purchase_bill_lines: PurchaseBillLines;
  purchase_bills: PurchaseBills;
  purchase_order_lines: PurchaseOrderLines;
  purchase_orders: PurchaseOrders;
  receipts: Receipts;
  role_permissions: RolePermissions;
  roles: Roles;
  sales_invoice_lines: SalesInvoiceLines;
  sales_invoices: SalesInvoices;
  sales_order_lines: SalesOrderLines;
  sales_orders: SalesOrders;
  sales_quote_lines: SalesQuoteLines;
  sales_quotes: SalesQuotes;
  sessions: Sessions;
  tax_codes: TaxCodes;
  tax_rates: TaxRates;
  tds_codes: TdsCodes;
  uoms: Uoms;
  user_companies: UserCompanies;
  user_roles: UserRoles;
  users: Users;
}
